version: '3.7'
services:
  db:
    image: mysql:5.7
    volumes:
      # 永続化するときにマウントするフォルダー
      - ./DB/mysql_data:/var/lib/mysql
      - ./DB:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pass #←デフォルトのパスワード
    ports:
      - '13306:3306' #ポート 13306でコンテナにアクセス
    command: [
        'mysqld',
        '--character-set-server=utf8mb4', #絵文字を入れられるように文字コード変更
        '--collation-server=utf8mb4_unicode_ci',
      ]
